### ISSUE TITLE
Crashing for a boarding Pass

### ISSUE THREAD

**Issue by inboxme98** [anomaddev/BoardingPassKit#4]
@anomaddev 

Parser is crasing for a Boarding Pass , Could you please fix this 

"M1AIGOZHINA/ELMIRA    EPYP98I NQZALAKC 7773 332Y013K0001 31C>2080      B0E             0"

**Comment by anomaddev** [comment]
The string of data provided is not valid which is why the decoder is throwing an error. There are other parsers out there that will validate this. Double check you are getting the full data from the barcode on the pass. 

[Check this here](https://www.flighthistorian.com/boarding-pass/results/M1AIGOZHINA%2FELMIRA%20EPYP98I%20NQZALAKC%207773%20332Y013K0001%2031C%3E2080%20B0E%200)

**Comment by devpolant** [comment]
Hi @anomaddev,

I think @inboxme98 meant that `BoardingPassDecoder` is not throwing an error, but it's crashing at the following line:

BoardingPassDecoder.swift - Line 180
BoardingPassDecoder.readdata(_:) + 180

```swift
let subdata = data.subdata(in: index ..< (index + length))
```

Yes, it might be due to invalid input string, but even in that case you expect a validation/parsing error to be thrown but not decoder to be crashed.

What I'm trying to say that it's better to check the `data.indices` first before accessing `data.subdata(...)` - if range is invalid, then throw an additional `BoardingPassError`, but do not try to access **subdata** without validating the `index ..< (index + length)`.

For example:

```swift
guard length > 0 else {
    return ""
}
let subrange = index ..< (index + length)
guard
    data.indices.contains(subrange.lowerBound),
    data.indices.contains(subrange.upperBound - 1)
else {
    throw BoardingPassError.InvalidRange
}
let subdata = data.subdata(in: subrange)
// ...
```
